<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<title>Untitled Document</title>
<style type="text/css">
#lit
{width:1000px;
 height:1000px;
 background-image:-webkit-linear-gradient(top left,#FF0000 0%,#00FF00 100%);
}
</style>
</head>
<body>

<div id="lit"></div>
</body>
</html>
